import localFont from "next/font/local"
// import { Red_Hat_Display } from 'next/font/google'

// Supports weights 300-900
// import redHat from '@fontsource-variable/red-hat-display'
import "./globals.css"
// import Head from "next/head"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

// const redHat = Red_Hat_Display({
//   subsets: ["latin"],
//   // weight: "100 900"
// })

export const metadata = {
  title: "WEB TECHNICODERS",
  description: "Generated by create TECHNICODERS",
  keywords: "TECHNICODERS",
  author: "TECHNICODERS"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0E1629]`}
      >
        {children}
      </body>
    </html>
  )
}
