import localFont from "next/font/local"
import "./globals.css"
import Head from "next/head"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata = {
  title: "WEB TECHNICODERS",
  description: "Generated by create TECHNICODERS",
  keywords: "TECHNICODERS",
  author: "TECHNICODERS"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0E1629]`}
      >
        {children}
      </body>
    </html>
  )
}
